site_name: High Ping Network Official Website
site_url: "https://highp.ing/"
site_author: "High Ping"
site_description: "High Ping Network Official Website"
repo_url: "https://github.com/High-Ping-Network/highp.ing"

#theme:
#  name: material